# Generated by Django 5.0 on 2023-12-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('dashboard', models.CharField(max_length=500)),
                ('imagen', models.ImageField(upload_to='portafolio/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.categoria')),
            ],
        ),
    ]
