# Generated by Django 5.0 on 2023-12-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='numero_telefono',
            field=models.CharField(max_length=255),
        ),
    ]
